version: "3.7"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - inventory_manager

  remix:
    container_name: frontend
    build: ./frontend/.
    ports:
      - "3000:3000"
      - "3001:3001"
      - "5555:5555"
    environment:
      WATCHPACK_POLLING: ${WATCHPACK_POLLING}
      CHOKIDAR_USEPOLLING: ${CHOKIDAR_USEPOLLING}
      NODE_ENV: ${NODE_ENV}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_URL: ${DATABASE_URL}

    volumes:
      - ./frontend:/app
    networks:
      - inventory_manager

networks:
  inventory_manager:
    driver: bridge
